### ISSUE TITLE
更新py_ios_device,pymobiledevice3后运行起来报错

### ISSUE THREAD

**Issue by WINGSIGOD** [15525730080/iOS17_perf#4]
你好 我本地使用2024/5/22新的
```
py-ios-device             2.4.12
pymobiledevice3           4.8.2
```
出现报错
```terminal
Identifier: 00008101-000250E60201001E
Interface: pywintun
Protocol: TunnelProtocol.QUIC
RSD Address: fdb6:680b:23ee::1
RSD Port: 61081
Use the follow connection option:
--rsd fdb6:680b:23ee::1 61081
Exception in thread Thread-2 (ios17_proc_perf):
Traceback (most recent call last):
  File "C:\Users\huangzhengtao\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "C:\Users\huangzhengtao\AppData\Local\Programs\Python\Python310\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "D:\workspace\ios17_perf\main.py", line 77, in ios17_proc_perf
    with RemoteLockdownClient((self.host, self.port)) as rsd:
  File "D:\workspace\venv\lib\site-packages\ios_device\remote\remote_lockdown.py", line 27, in __init__
    super().__init__(address=address)
  File "D:\workspace\venv\lib\site-packages\ios_device\util\lockdown.py", line 64, in __init__
    self.connect()
  File "D:\workspace\venv\lib\site-packages\ios_device\remote\remote_lockdown.py", line 41, in connect
    self.service.connect()
  File "D:\workspace\venv\lib\site-packages\ios_device\remote\remotexpc.py", line 38, in connect
    self.sock = create_connection(self.address)
  File "C:\Users\huangzhengtao\AppData\Local\Programs\Python\Python310\lib\socket.py", line 845, in create_connection
    raise err
  File "C:\Users\huangzhengtao\AppData\Local\Programs\Python\Python310\lib\socket.py", line 833, in create_connection
    sock.connect(sa)
TimeoutError: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。
Exception in thread Thread-3 (ios17_fps_perf):
Traceback (most recent call last):
  File "C:\Users\huangzhengtao\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "C:\Users\huangzhengtao\AppData\Local\Programs\Python\Python310\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "D:\workspace\ios17_perf\main.py", line 96, in ios17_fps_perf
    with RemoteLockdownClient((self.host, self.port)) as rsd:
  File "D:\workspace\venv\lib\site-packages\ios_device\remote\remote_lockdown.py", line 27, in __init__
    super().__init__(address=address)
  File "D:\workspace\venv\lib\site-packages\ios_device\util\lockdown.py", line 64, in __init__
    self.connect()
  File "D:\workspace\venv\lib\site-packages\ios_device\remote\remote_lockdown.py", line 41, in connect
    self.service.connect()
  File "D:\workspace\venv\lib\site-packages\ios_device\remote\remotexpc.py", line 38, in connect
    self.sock = create_connection(self.address)
  File "C:\Users\huangzhengtao\AppData\Local\Programs\Python\Python310\lib\socket.py", line 845, in create_connection
    raise err
  File "C:\Users\huangzhengtao\AppData\Local\Programs\Python\Python310\lib\socket.py", line 833, in create_connection
    sock.connect(sa)
TimeoutError: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。
```
想咨询一下是我本地问题还是作者需要更新源码呢?
谢谢

**Comment by 15525730080** [comment]
> 你好 我本地使用2024/5/22新的
> 
> ```
> py-ios-device             2.4.12
> pymobiledevice3           4.8.2
> ```
> 
> 出现报错
> 
> ```
> Identifier: 00008101-000250E60201001E
> Interface: pywintun
> Protocol: TunnelProtocol.QUIC
> RSD Address: fdb6:680b:23ee::1
> RSD Port: 61081
> Use the follow connection option:
> --rsd fdb6:680b:23ee::1 61081
> Exception in thread Thread-2 (ios17_proc_perf):
> Traceback (most recent call last):
>   File "C:\Users\huangzhengtao\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1016, in _bootstrap_inner
>     self.run()
>   File "C:\Users\huangzhengtao\AppData\Local\Programs\Python\Python310\lib\threading.py", line 953, in run
>     self._target(*self._args, **self._kwargs)
>   File "D:\workspace\ios17_perf\main.py", line 77, in ios17_proc_perf
>     with RemoteLockdownClient((self.host, self.port)) as rsd:
>   File "D:\workspace\venv\lib\site-packages\ios_device\remote\remote_lockdown.py", line 27, in __init__
>     super().__init__(address=address)
>   File "D:\workspace\venv\lib\site-packages\ios_device\util\lockdown.py", line 64, in __init__
>     self.connect()
>   File "D:\workspace\venv\lib\site-packages\ios_device\remote\remote_lockdown.py", line 41, in connect
>     self.service.connect()
>   File "D:\workspace\venv\lib\site-packages\ios_device\remote\remotexpc.py", line 38, in connect
>     self.sock = create_connection(self.address)
>   File "C:\Users\huangzhengtao\AppData\Local\Programs\Python\Python310\lib\socket.py", line 845, in create_connection
>     raise err
>   File "C:\Users\huangzhengtao\AppData\Local\Programs\Python\Python310\lib\socket.py", line 833, in create_connection
>     sock.connect(sa)
> TimeoutError: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。
> Exception in thread Thread-3 (ios17_fps_perf):
> Traceback (most recent call last):
>   File "C:\Users\huangzhengtao\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1016, in _bootstrap_inner
>     self.run()
>   File "C:\Users\huangzhengtao\AppData\Local\Programs\Python\Python310\lib\threading.py", line 953, in run
>     self._target(*self._args, **self._kwargs)
>   File "D:\workspace\ios17_perf\main.py", line 96, in ios17_fps_perf
>     with RemoteLockdownClient((self.host, self.port)) as rsd:
>   File "D:\workspace\venv\lib\site-packages\ios_device\remote\remote_lockdown.py", line 27, in __init__
>     super().__init__(address=address)
>   File "D:\workspace\venv\lib\site-packages\ios_device\util\lockdown.py", line 64, in __init__
>     self.connect()
>   File "D:\workspace\venv\lib\site-packages\ios_device\remote\remote_lockdown.py", line 41, in connect
>     self.service.connect()
>   File "D:\workspace\venv\lib\site-packages\ios_device\remote\remotexpc.py", line 38, in connect
>     self.sock = create_connection(self.address)
>   File "C:\Users\huangzhengtao\AppData\Local\Programs\Python\Python310\lib\socket.py", line 845, in create_connection
>     raise err
>   File "C:\Users\huangzhengtao\AppData\Local\Programs\Python\Python310\lib\socket.py", line 833, in create_connection
>     sock.connect(sa)
> TimeoutError: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。
> ```
> 
> 想咨询一下是我本地问题还是作者需要更新源码呢? 谢谢
windows本地装一下 itunes，这个是因为windows 缺少usbmud 去和ios 设备通信。另外。 黄正涛你的名字暴露了

**Comment by WINGSIGOD** [comment]
好的
